name: bioml
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - scikit-learn
  - seaborn
  - jupyter
  - numpy
  - pandas
  - biopython
  - trimmomatic
  - fastqc
  - samtools
  - hisat2
  - sra-tools
  - seqtk
